export const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export const link=(href,label,cls='')=>`<a class="${cls}" href="${href}">${label}</a>`;
export const sameRoute=(href,path)=>href===path||(`${href}/`===path);
export const title=(k,h,p='')=>`<div class="sectionTitle reveal"><span>${k}</span><h2>${h}</h2>${p?`<p>${p}</p>`:''}</div>`;
export const cta=(h,p,b='Nous contacter',href='/contact',b2='',href2='')=>`<section class="ctaSection"><div class="finalCta reveal"><div><span>Prochaine étape</span><h2>${h}</h2><p>${p}</p></div><div class="ctaActions">${link(href,b,'btn primary')}${b2?link(href2,b2,'btn secondary'):''}</div></div></section>`;
export const iconGlyph=t=>({cert:'✓',web:'◫',saas:'⌁',connect:'◇',crm:'C',partner:'P',cpf:'€',of:'OF',growth:'↗',shield:'◈',data:'∷',design:'✦',default:'✦'}[t]||t||'✦');
export const card=(t,p,href='',points=[],icon='default')=>`<article class="card reveal"><div class="icon">${iconGlyph(icon)}</div><h3>${t}</h3><p>${p}</p>${points.length?`<ul>${points.map(x=>`<li>${x}</li>`).join('')}</ul>`:''}${href?link(href,'Découvrir','cardLink'):''}</article>`;
export const listCards=items=>items.map(([t,p])=>card(t,p)).join('');
export const steps=items=>`<div class="steps">${items.map((s,i)=>`<p class="reveal"><b>0${i+1}</b>${s}</p>`).join('')}</div>`;

export const heroVisual=(variant='network')=>`<div class="heroVisual visual-${variant}" aria-hidden="true"><div class="visualOrb"></div><div class="visualFrame"><span></span><span></span><span></span><span></span></div><svg viewBox="0 0 520 420" role="img" aria-label="Illustration abstraite premium"><defs><linearGradient id="g-${variant}" x1="0" x2="1"><stop stop-color="#F4C45A"/><stop offset="1" stop-color="#4aa3ff"/></linearGradient><filter id="glow-${variant}"><feGaussianBlur stdDeviation="5" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><path class="gridLine" d="M72 88H448M72 166H448M72 244H448M72 322H448M128 48V370M246 48V370M364 48V370"/><path class="flowLine" stroke="url(#g-${variant})" d="M96 306C156 226 208 282 260 196S362 94 430 122"/><path class="flowLine alt" stroke="url(#g-${variant})" d="M96 142C162 104 206 154 260 152C330 150 352 230 426 206"/><g filter="url(#glow-${variant})"><circle class="node gold" cx="96" cy="306" r="9"/><circle class="node" cx="260" cy="196" r="12"/><circle class="node gold" cx="430" cy="122" r="10"/><circle class="node" cx="426" cy="206" r="8"/></g><rect class="module m1" x="118" y="86" width="108" height="70" rx="18"/><rect class="module m2" x="288" y="242" width="124" height="82" rx="20"/><rect class="module m3" x="174" y="256" width="72" height="52" rx="16"/></svg></div>`;

export const sectionIllustration=(variant='architecture',label='Architecture visuelle')=>`<article class="sectionIllustration reveal visual-${variant}" aria-label="${label}"><div class="visualCaption"><span>${label}</span><b>${variant==='web'?'Interfaces flottantes':variant==='cert'?'Référentiel validé':variant==='company'?'Pilotage groupe':'Architecture connectée'}</b></div>${heroVisual(variant)}</article>`;
export const moduleDiagram=(items)=>`<div class="moduleDiagram reveal">${items.map((it,i)=>`<div class="moduleNode node${i}"><i>${iconGlyph(it.icon)}</i><b>${it.title}</b><span>${it.text}</span></div>`).join('')}<div class="diagramCore"><strong>Intégrale<br>Connect</strong></div></div>`;
export const interactionDiagram=()=>moduleDiagram([{title:'Certifications',text:'Référentiels & conformité',icon:'cert'},{title:'Webdesign',text:'Image & conversion',icon:'web'},{title:'SaaS',text:'Automatisation métier',icon:'saas'},{title:'Connect',text:'Suite modulaire OF',icon:'connect'}]);
