import { iconGlyph } from '../../scripts/html.mjs';

const panel=(cls,inner,label='Visuel abstrait')=>`<div class="premiumVisual ${cls}" aria-label="${label}" role="img"><div class="visualGrid"></div><div class="lightBeam"></div>${inner}</div>`;
const dots=n=>Array.from({length:n},(_,i)=>`<i style="--i:${i}"></i>`).join('');
const metric=(k,v)=>`<span class="metric"><b>${k}</b><small>${v}</small></span>`;
const rails=(n=3)=>`<div class="signalRails">${Array.from({length:n},()=>'<span></span>').join('')}</div>`;

export const HeroVisualGroup=()=>panel('heroVisualGroup',`<div class="groupCore"><b>IG</b><span>formation & terrain</span><small>conseil · digital · outils métier</small></div><div class="growthPath"></div><div class="orbitNodes">${['Formation','Conseil','Digital','Suivi','Méthode','Emploi'].map(x=>`<em>${x}</em>`).join('')}</div><div class="barStack"><span></span><span></span><span></span></div><div class="microDashboard">${metric('Depuis','2018')}${metric('Academy','Socle')}${metric('Outils','Métier')}</div>${rails(3)}${dots(24)}`,'Structuration, croissance et interconnexion');

export const AcademyVisual=()=>panel('academyHeroVisual',`<div class="academyVisualBrand"><i>IA</i><b>Intégrale Academy</b><small>Former pour agir</small></div><article class="academyVisualSince"><small>Depuis</small><b>2018</b></article><article class="academyVisualQuality"><i>Q</i><b>Qualiopi</b><small>Démarche qualité</small></article><article class="academyVisualCampus"><small>Campus</small><b>Puget-sur-Argens</b></article><div class="academyVisualCourses"><span>APS</span><span>A3P</span><span>SSIAP 1</span><span>VTC</span><span>BTS</span><span>VAE</span></div>`,'Intégrale Academy, organisme de formation professionnelle fondé en 2018 à Puget-sur-Argens');

export const CertificationVisual=()=>panel('certificationVisual',`<div class="certDoc main"><header><strong>DSSP</strong><small>RNCP dossier</small></header><span></span><span></span><div class="certMatrix"><b>Blocs</b><i></i><i></i><i></i><i></i></div><ul><li>Référentiel</li><li>Preuves</li><li>Jury</li></ul></div><div class="certDoc side"><b>Conformité</b><small>France Compétences</small><em>86%</em></div><div class="evidenceStack"><span>Évaluation</span><span>Traçabilité</span><span>Qualité</span></div><div class="checkRing">✓</div><div class="sealMark">RNCP</div><div class="complianceLines"><span></span><span></span><span></span><span></span></div>`,'Système premium de validation, référentiel RNCP, preuves et conformité');

export const ExpertisesVisual=()=>panel('expertisesVisual',`<div class="expertisesVisualCore"><span>INTÉGRALE</span><b>EXPERTISES</b><small>Ingénierie de certification</small></div><div class="expertisesVisualMetric registration"><b>05</b><span>En cours d’enregistrement</span></div><div class="expertisesVisualMetric writing"><b>05</b><span>En cours d’écriture</span></div><div class="expertisesVisualTags"><span>Référentiels</span><span>Évaluation</span><span>Traçabilité</span></div><div class="expertisesVisualSeal">France<br>compétences</div>`,'Intégrale Expertises, ingénierie de certification professionnelle et portefeuille de dix projets de titres');

export const ConseilVisual=()=>panel('conseilHeroVisual',`<div class="conseilVisualCore"><i>03</i><b>Votre organisation</b><small>Le point de départ</small></div><div class="conseilVisualSteps">${[['01','Comprendre'],['02','Prioriser'],['03','Structurer'],['04','Accompagner']].map(([n,t],i)=>`<article class="cvs${i+1}"><i>${n}</i><b>${t}</b><span></span></article>`).join('')}</div><div class="conseilVisualResult"><small>Cap</small><b>Clair & exploitable</b><span>Décisions · outils · déploiement</span></div><div class="conseilVisualInputs"><span>Équipe</span><span>Outils</span><span>Contraintes</span><span>Objectifs</span></div><svg class="conseilVisualPath" viewBox="0 0 600 500" aria-hidden="true"><path d="M300 245C215 245 196 138 112 138M300 245C385 245 404 138 488 138M300 245C215 245 196 362 112 362M300 245C385 245 404 362 488 362"/><circle cx="300" cy="245" r="116"/><path class="pulse" d="M92 420C190 470 420 470 508 420"/></svg>`,'Méthode du pôle conseil : comprendre, prioriser, structurer et accompagner une organisation');

export const DigitalVisual=()=>panel('digitalHeroVisual',`<div class="digitalVisualScreen"><header><span><i></i><i></i><i></i></span><b>interface-metier.app</b></header><aside><i>IG</i><span></span><span></span><span></span><span></span></aside><main><small>TABLEAU DE BORD</small><div class="digitalVisualStats"><article><b>CRM</b><span>Pipeline</span></article><article><b>DOCS</b><span>Suivi</span></article><article><b>AUTO</b><span>Flux</span></article></div><div class="digitalVisualChart"><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="digitalVisualRows"><p><i></i><span></span><b>Traité</b></p><p><i></i><span></span><b>En cours</b></p><p><i></i><span></span><b>Validé</b></p></div></main></div><article class="digitalVisualWebsite"><i>WEB</i><b>Site & interface</b><span></span><span></span><button>CTA</button></article><article class="digitalVisualAutomation"><i>↗</i><b>Automatisation</b><small>Processus → action</small><span></span></article><div class="digitalVisualTags"><span>API</span><span>PDF</span><span>WEBHOOK</span><span>CRM</span></div><svg class="digitalVisualFlow" viewBox="0 0 600 500" aria-hidden="true"><path d="M123 160C215 190 224 229 302 248M478 351C397 325 382 283 302 248"/><circle cx="302" cy="248" r="126"/><path class="alt" d="M92 432C207 475 405 472 514 412"/></svg>`,'Pôle digital : site web, interface métier, CRM, automatisations et tableau de bord connectés');

export const WebdesignVisual=()=>panel('webdesignVisual',`<div class="screen desktop"><header><i></i><i></i><i></i></header><section></section><div class="uiRows"><p></p><p></p><p></p></div><div class="conversionCard"><b>CTA</b><span>+18%</span></div><button></button></div><div class="screen tablet"><header></header><p></p><div class="tileGrid"><i></i><i></i><i></i><i></i></div></div><div class="screen mobile"><header></header><span></span><span></span><span></span><b></b></div><div class="designSystem"><span>Typography</span><span>Components</span><span>Grid 12</span></div><div class="cursorPath"></div>${rails(2)}`,'Mockups desktop et mobile, design system, landing page et conversion');

export const SaasVisual=()=>panel('saasVisual',`<div class="dash"><header><b></b><b></b><b></b></header><main><span><i></i></span><span><i></i></span><span><i></i></span><span><i></i></span></main><footer>${metric('Docs','PDF')}${metric('CRM','Live')}</footer></div><div class="apiCloud">API</div><div class="dbCylinder"><i></i><i></i><b>DATA</b></div><div class="automationLine"></div><div class="moduleMesh">${['CRM','PDF','DATA','AUTO','CLOUD','WEBHOOK'].map(x=>`<em>${x}</em>`).join('')}</div><svg class="saasFlow" viewBox="0 0 600 420" aria-hidden="true"><path d="M142 292C214 248 268 250 332 298S470 316 510 214"/><path class="alt" d="M164 104C238 156 335 154 424 92"/></svg>`,'Architecture SaaS avec modules, API, automatisation, données et cloud');

export const ConnectVisual=()=>panel('connectVisual',`<div class="connectDash"><b>Intégrale Connect</b><span>hub centralisé</span><div class="hubStats">${metric('Lead','CRM')}${metric('OF','Docs')}${metric('CPF','Suivi')}</div></div><div class="connectModules">${[['CRM','C','Pipeline · relances'],['Partenaires','P','Conventions · dossiers'],['CPF','€','Statuts · paiements'],['Gestion OF','OF','Sessions · qualité']].map(([t,g,s],i)=>`<article class="cm cm${i}"><i>${g}</i><strong>${t}</strong><small>${s}</small><span></span></article>`).join('')}</div><div class="connectHalo"></div><svg viewBox="0 0 600 420" aria-hidden="true"><path d="M300 210C160 76 126 96 102 122M300 210C440 76 474 96 498 122M300 210C160 344 126 324 102 298M300 210C440 344 474 324 498 298"/><path class="alt" d="M102 122C220 178 380 178 498 122M102 298C220 242 380 242 498 298"/><circle cx="300" cy="210" r="118"/><circle class="alt" cx="300" cy="210" r="176"/></svg><div class="dataPoints"><i></i><i></i><i></i><i></i><i></i><i></i></div>`,'Écosystème logiciel Intégrale Connect avec CRM, partenaires, CPF, Gestion OF et hub central');

export const CompanyVisual=()=>panel('companyHeroVisual',`<div class="companyVisualHeader"><span>INTÉGRALE GROUP</span><i>SAS · 2025</i></div><div class="companyVisualCore"><small>STRUCTURE GROUPE</small><b>PILOTER</b><span>Vision · Coordination · Développement</span></div><div class="companyVisualMetrics"><article><b>2018</b><span>Origine terrain</span></article><article><b>04</b><span>Pôles métiers</span></article><article><b>1,041 M€</b><span>Capital social</span></article></div><div class="companyVisualAxes">${[['01','Former'],['02','Certifier'],['03','Structurer'],['04','Outiller']].map(([n,t])=>`<article><i>${n}</i><b>${t}</b></article>`).join('')}</div><div class="companyVisualLegal"><span>SIREN</span><b>989 785 068</b></div><svg class="companyVisualNetwork" viewBox="0 0 600 500" aria-hidden="true"><path d="M300 238C215 238 194 130 103 130M300 238C385 238 406 130 497 130M300 238C215 238 194 372 103 372M300 238C385 238 406 372 497 372"/><circle cx="300" cy="238" r="132"/><path class="alt" d="M92 438C208 484 398 480 510 430"/></svg>`,'Intégrale Group : structure centrale, quatre pôles métiers, gouvernance et capital social');

export const HistoryVisual=()=>panel('historyVisual',`<div class="historyVisualStamp">Depuis<br>2018</div><div class="historyVisualOrbit one"></div><div class="historyVisualOrbit two"></div><div class="historyVisualCore"><b>2018</b><span>Le point de départ</span></div>${[['Terrain','tag1'],['Formation','tag2'],['Méthode','tag3'],['Digital','tag4']].map(([text,cls])=>`<em class="historyVisualTag ${cls}">${text}</em>`).join('')}`,'Une trajectoire née du terrain en 2018, devenue un écosystème de formation, de conseil et de solutions digitales');

export const ContactVisual=()=>panel('contactHeroVisual',`<div class="contactVisualHeader"><span>NOUVELLE DEMANDE</span><i>INTÉGRALE GROUP</i></div><article class="contactVisualMessage"><small>VOTRE PROJET</small><b>Un besoin à qualifier.</b><span></span><span></span><div><i>Contexte</i><i>Objectif</i><i>Calendrier</i></div></article><div class="contactVisualRoute"><span>Orientation</span><b>Le bon pôle</b><small>Formation · Expertises · Conseil · Digital</small></div><div class="contactVisualTopics">${[['IA','Formation'],['IE','Expertises'],['CA','Conseil'],['DG','Digital']].map(([code,label])=>`<article><i>${code}</i><b>${label}</b></article>`).join('')}</div><div class="contactVisualStatus"><i></i><span>Échange qualifié</span><b>→</b></div><svg class="contactVisualFlow" viewBox="0 0 600 500" aria-hidden="true"><path d="M302 240C215 240 190 128 95 128M302 240C389 240 414 128 509 128M302 240C215 240 190 378 95 378M302 240C389 240 414 378 509 378"/><circle cx="302" cy="240" r="128"/><path class="alt" d="M92 438C216 480 399 474 510 428"/></svg>`,'Contact Intégrale Group : une demande qualifiée puis orientée vers la formation, les expertises, le conseil ou le digital');

export const ExpertiseNetworkVisual=()=>panel('expertiseNetworkVisual',`<div class="expertiseCore"><i>IG</i><b>Intégrale Group</b><small>une vision commune</small></div>${[['Formation','Compétences & emploi','of'],['Expertises','Certification','cert'],['Conseil','Organisation','growth'],['Digital','Outils métiers','web']].map(([t,s,i],n)=>`<article class="xp xp${n}"><i>${iconGlyph(i)}</i><div><b>${t}</b><small>${s}</small></div></article>`).join('')}<svg viewBox="0 0 900 420"><path d="M450 210L170 92M450 210L730 92M450 210L170 328M450 210L730 328"/></svg>`,'Les quatre pôles d’Intégrale Group : formation, expertises, conseil et digital');

export const ModuleFlowVisual=()=>panel('moduleFlowVisual',`${['Processus','Automatisation','Dashboard'].map((x,i)=>`<article><i>0${i+1}</i><b>${x}</b><span></span><span></span></article>`).join('')}<div class="flowArrow"></div>`,'Processus vers automatisation puis dashboard');

export const DashboardMockupVisual=()=>panel('dashboardMockupVisual',`<div class="mockNav"></div><div class="mockChart"><span></span><span></span><span></span></div><div class="mockCards"><i></i><i></i><i></i></div>`,'Tableau de bord stylisé');

export const ProcessTimelineVisual=(items=['Création','Vision','Pôles','Croissance'])=>`<div class="processTimelineVisual reveal">${items.map((x,i)=>`<article><i>0${i+1}</i><b>${x}</b><span></span></article>`).join('')}</div>`;

export const visualForRoute=route=>({
 '/':HeroVisualGroup,
 '/les-poles-du-groupe':ExpertiseNetworkVisual,
 '/pole-formation':AcademyVisual,
 '/integrale-expertises':ExpertisesVisual,
 '/pole-conseil-accompagnement':ConseilVisual,
 '/pole-developpement-web':DigitalVisual,
 '/notre-histoire':HistoryVisual,
 '/certifications':CertificationVisual,
 '/webdesign':WebdesignVisual,
 '/developpement-saas':SaasVisual,
 '/integrale-connect':ConnectVisual,
 '/entreprise':CompanyVisual,
 '/contact':ContactVisual
}[route]||HeroVisualGroup)();
