import { company } from '../data/siteContent.mjs';
import { card, cta, title } from '../scripts/html.mjs';
export const route = '/';
export const buttons = '<a class="btn primary" href="#expertises">Découvrir nos expertises</a><a class="btn secondary" href="/contact?sujet=partenariat">Devenir partenaire</a>';
export function render(){
const poles=[['Certifications professionnelles','Structuration de projets de certification, référentiels, blocs de compétences, modalités d’évaluation et préparation des relations partenaires.','/certifications',['Ingénierie de certification','Conformité et preuves','Réseau partenaire']],['Webdesign premium','Création de sites élégants, crédibles et orientés conversion pour transformer une expertise réelle en présence digitale rassurante.','/webdesign',['Direction artistique','Contenus structurés','Mobile et conversion']],['Développement SaaS','Conception de plateformes métier, CRM, automatisations et tableaux de bord pour fiabiliser les opérations quotidiennes.','/developpement-saas',['Process sur mesure','Données centralisées','Maintenance évolutive']],['Intégrale Connect','Écosystème digital dédié aux organismes de formation pour suivre prospects, dossiers, partenaires, CPF et documents.','/integrale-connect',['CRM formation','Gestion partenaires','Pilotage administratif']]];
const why=[['Vision stratégique','Nous partons du modèle économique, des contraintes terrain et des objectifs de croissance avant de concevoir les supports.'],['Qualité d’exécution','Chaque livrable est pensé pour être présentable, exploitable et cohérent avec une image d’entreprise sérieuse.'],['Culture terrain','Les parcours, outils et contenus sont construits autour des usages réels, pas seulement autour d’une intention marketing.'],['Design premium','Interfaces sobres, hiérarchie claire, contrastes maîtrisés et détails visuels qui renforcent la confiance.'],['Fiabilité technique','Développement propre, responsive, maintenable et prêt pour des évolutions progressives.'],['Croissance long terme','Une logique de structuration durable pour accompagner le développement commercial et opérationnel.']];
return `<section class="intro">${title('Un groupe au service de la structuration','Professionnaliser l’image, les outils et les processus','Intégrale Group réunit plusieurs expertises complémentaires pour accompagner les structures qui veulent professionnaliser leur image, leurs outils, leurs processus et leur développement. Notre approche associe vision stratégique, exigence réglementaire, design digital et solutions techniques sur mesure.')}</section><section id="expertises">${title('Nos pôles d’expertise','Quatre expertises activables seules ou ensemble','Chaque pôle répond à un besoin précis : crédibiliser une offre, créer un actif digital, automatiser une organisation ou structurer un réseau partenaire.')}<div class="grid four">${poles.map(p=>card(...p)).join('')}</div></section><section class="band"><div>${title('Approche','Une approche pensée pour les organismes ambitieux','Nous aidons les structures à clarifier leur positionnement, organiser leurs parcours, renforcer leur crédibilité et installer des outils qui fluidifient le quotidien.')}</div><div class="bullets"><p>Clarification de l’offre et des messages clés</p><p>Structuration des parcours et documents</p><p>Amélioration de l’image et de la réassurance</p><p>Automatisation des process administratifs</p><p>Développement de la croissance commerciale</p></div></section><section>${title('Chiffres clés','Des bases lisibles et solides')}<div class="stats"><b><span>SAS au capital de</span>${company.capital}</b><b><span>SIREN</span>${company.siren}</b><b><span>Basé à</span>Puget-sur-Argens</b><b><span>Pôles</span>4 pôles d’expertise</b><b><span>Domaines</span>Certification, digital, SaaS, partenaires</b></div></section><section>${title('Pourquoi travailler avec Intégrale Group','Une exigence globale, de la stratégie à l’exécution')}<div class="grid three">${why.map(x=>card(x[0],x[1])).join('')}</div></section>${cta('Vous avez un projet à structurer, digitaliser ou développer ?','Échangeons sur votre besoin et construisons une solution claire, professionnelle et évolutive.','Nous contacter','/contact','Devenir partenaire','/contact?sujet=partenariat')}`;
}
